.TH HTOP 1 "July 1999" "pftools 2.2"
.SH NAME
htop \- convert a HMMER ASCII-formatted HMM into an equivalent profile  
.SH SYNOPSIS
.LP
.nf
\fBhtop\fP [ -fios ] [ hmm-file | - ] [ random-model-file ] [B=#]
        [C=#] [F=#] [H=#] [L=#] [M=#] [P=#] [Q=#] 
.fi
.SH DESCRIPTION
.B htop
converts a hidden Markov model (HMM) into an equivalent PROSITE-formatted generalized profile. 
.I hmm-file
is a nucleic acid or protein HMM in HMMER ascii-format.
.I random-model-file
contains a simple null-model in the format used by the HMM search programs
of the HMMER1 package.
This parameter is only effective in conjunction with the 
\-b option. If omitted, a random model consisting of the 
average residue probabilities of the insert states will be used.
.SH OPTIONS 
.TP
\-f
Emulate HMM fragment search (only effective with old HMMER1 format).
When given as input to the pftools programs
.B pfsearch 
or
.B pfscan,
the resulting profile will behave like the original HMM searched with 
the HMMER1 program 
.B hmmfs. 
The default mode is to emulate HMM local search implemented in the HMMER1 program 
.B hmmls. 
.TP
\-i
Force all insert extension scores to be zero.
.TP
\-o
Assume input to be in old HMMER1 format. Pftools version 2.2 assumes by default
HMMER2 format. 
.TP
\-s
Implement semiglobal alignment mode. This option forces all external
initiation scores to be identical to the internal initiation
score at the beginning of the profile. Likewise, the external 
termination scores are set to the value of the internal
termination score at the end of the profile.
.SH ADDITIONAL PARAMETERS 
.TP
B=#
Logarithmic base to be used for normalization of profile
match scores (only effective with old HMMER1 format).
Default: B=2.0.
.TP
C=#
Level zero cut-off value in normalized score units.
Default: C=8.5 (C=0.0 in conjunction with option 
-o).
.TP
F=#
Output score multiplier (only effective in conjunction with
old HMMER1 format). On output, all profile scores are multiplied by
this factor and rounded to the nearest integers. Default: F=100.
With the new HMMER2 format, which uses an integer-rounded
log-odds representation of the HMM parameters, the original values
cannot be rescaled. 
.TP
H=#
High-cost initiation/termination score (only effective in conjunction with 
-s option). This score will be applied to
all external and internal initiation and termination scores
at path matrix positions where
initiation or termination at low cost is not possible according to semiglobal
alignment mode.
Default: H=* (low-value).
.TP
L=#
Logarithmic base to be used for representation of profile
scores (only effective in conjunction with old HMMER1 format).
Default: 1.0233739 (1/30 bit units).
.TP
M=#
Maximal number of unprotected residues at the ends of the profile.
Default: M=5.
.TP
P=#
Percent profile-length at the ends of the profile,
which will not be included in the protected area
(may be overwritten by parameter 
.I M,
see above). Default: P=0.
.TP
Q=#
Position-independent odds ratio assumed for unknown residues.
This parameter determines 
the default values for profile scores
.I M0
and 
.I I0.
Note that the 
.I I0
scores may be over-written by the
.I -i   
option.
Default: Q=0.8.
.SH EXAMPLES
.TP
(1)
.B htop 
pfam_sh3.hmm > pfam_sh3.prf

Converts the HHMER2-formatted SH3 domain profile
in "pfam_sh3.hmm" into a generalized profile. 
After this conversion, the following two commands:

.B hmmsearch 
\--null2  pfam_sh3.hmm sh3.seq 
.br
.B pfsearch
\-fy pfam_sh3.prf sh3.seq C=5.0

should produce equivalent results in terms of raw scores
and profile-sequence alignments (E-values and normalized scores
will usually be different). Note that the program 
.B hmmsearch
is from Sean Eddy's HMMER2 package (http://hmmer.wustl.edu/).
.SH AUTHOR
Philipp Bucher
.br
Philipp.Bucher@isrec.unil.ch
