.TH PFSEARCH 1 "April 1997" "pftools 2.0"
.SH NAME
pfsearch \- search a protein or DNA sequence library for sequence segments 
matching a profile
.SH SYNOPSIS
.B pfsearch 
[ -abfrsuxyz ] [ profile-file | - ]
            [ seq-library-file | - ]    [C=#] 
.SH DESCRIPTION
.B pfsearch 
compares a query profile against a DNA or protein sequence library.
The result is an unsorted list of profile-sequence matches written to the standard output. 
A variety of output formats containing different informations can be specified 
via the options 
.I -a, -r, -u, -s,
.I -x, -y, -z,
and the command-line parameter 
.I C=#.
.I profile-file
contains a profile in PROSITE/NUCSITE format.
.I seq-library-file
contains a sequence library in EMBL/SWISS-PROT
format (assumed by default) or in Pearson/Fasta
format (indicated by option 
.I -f). 
.B pfsearch 
can be used as a filter if - is used instead of one of the input 
filenames. 
.SH OPTIONS 
.TP
\-a
Report optimal alignment scores for 
all sequences regardless of the cut-off value. 
This option simultaneously forces DISJOINT=UNIQUE.   
.TP
\-b
Search the complementary strands of DNA sequences as well.
.TP
\-f
Input sequence-library is in Pearson/Fasta format.
.TP
\-r
Use raw scores rather than normalized 
scores for match selection. Normalized scores 
will not be listed in the output. 
.TP
\-s
List the sequences of the matched regions as well. 
The output will be a Pearson/Fasta-formatted sequence
library.
.TP
\-u
Forces DISJOINT=UNIQUE. 
.TP
\-x
List profile-sequence alignments 
in pftools PSA format.  
.TP
\-y
Display alignments between the profile and the matched sequence regions in 
a human-friendly format.   
.TP
\-z
Indicate starting and ending position of the matched profile range. The latter
position will be given as a negative offset from the end of the profile. Thus
the range [    1,    -1] means entire profile.
.SH PARAMETERS 
.TP
C=#
Cut-off value.
Over-writes the level zero cut-off value specified in
the profile.
An integer argument is interpreted as a raw score value,
a decimal argument as a normalized score value. 
.SH EXAMPLES 
.TP
(1)
.B pfsearch
\-f sh3.prf sh3.seq C=6.0

Searches the Pearson/Fasta-formatted protein sequence library sh3.seq
for SH3 domains with a cut-off value of 6.0 normalized score units.
sh3.seq contains 20 SH3 domain-containing protein sequences from SWISS-PROT
release 32.
sh3.prf contains the PROSITE entry SH3/PS50002.
.TP
(2)
.B pfsearch
\-bx ecp.prf CVPBR322 |
.B psa2msa   
\-du |    
.B readseq
\-p -fMSF > ecp.msf

Generates a multiple sequence alignment  of potential
.I E. coli
promoters on both strands of plasmid pBR322.
ecp.prf contains a profile for
.I E. coli   
promoters.  
CVPBR322 contains EMBL entry J01749|CVPBR322.
The result file
.I ecp.msf   
can further be processed by GCG programs accepting MSF files as input.

.I See
also manual pages of 
.B psa2msa. 
.SH BUGS
.B pfsearch 
neither supports circular profiles nor circular sequences.
.SH AUTHOR
Philipp Bucher
.br
pbucher@isrec-sun1.unil.ch
